config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'articles#index'

  resources :articles do
    resources :comments, only: [:create, :update, :destroy]
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  belongs_to :user

  has_attached_file :picture, :styles => { :medium => "500x500>", :thumb => "150x150>" }
  validates_attachment_content_type :picture, :content_type => /\Aimage/

  default_scope { order(created_at: :desc) }

  validates :title, :user, presence: true
  validates :content, presence: true, length: { minimum: 10 }

  def published_at
    created_at.strftime("%Y-%m-%d")
  end

  def author
    user.username
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user

  default_scope { order(created_at: :desc) }

  validates :content, :article, presence: true

  def posted_at
    created_at.strftime("%Y-%m-%d %H:%M")
  end

  def author
    user.try :username
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles

  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  validates :username, presence: true
  validates :role, presence: true

  enum role: { user: 0, admin: 1 }

  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  def has_access_to? object
    self == object.try(:user) or self.admin?
  end

  #To log in using username
  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :role
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :create, :destroy]
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, only: [:update, :destroy]

  def index
    @articles = Article.all
  end

  def show
    @comment = Comment.new
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = current_user.articles.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :content, :picture)
    end

    def authorize_user
      raise 'Unauthorized' unless current_user.has_access_to? @article
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:update, :destroy]
  before_action :set_comment, only: [:update, :destroy]
  before_action :set_article
  before_action :authorize_user, only: [:update, :destroy]

  def create
    @comment = @article.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.json { render json: @comment, status: :created }
        format.js   { }
      else
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.json { render json: @comment, status: :ok }
      else
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.json { head :no_content }
      format.js   { }
    end
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:content)
    end

    def set_article
      @article = Article.find(params[:article_id])
    end

    def authorize_user
      raise 'Unauthorized' unless current_user.has_access_to? @comment
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_article.html.erb
<hr>

<h2>
  <a href="<%= url_for article %>">
    <%= article.title %>
  </a>
</h2>

<% if article.picture.exists? %>
    <a href="<%= url_for article %>">
      <%= image_tag article.picture.url :thumb %>
    </a>
<% end %>

<p>
  Posted on: <%= article.published_at %>
  By: <%= article.author %>
</p>

<% if current_user.try :has_access_to?, article %>
    <%= link_to 'Edit', edit_article_path(article) %>
    <%= link_to 'Delete', article, method: :delete, data: {confirm: 'Are you sure?'} %>
<% end %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
    <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

          <ul>
            <% @article.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :content %><br>
      <%= f.text_area :content %>
    </div>
    <div class="field">
      <%= f.label :picture %><br>
      <%= f.file_field :picture %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<% if current_user %>
    <%= link_to 'New Article', new_article_path %>
    <br>
<% end %>

<%= render @articles %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>By <b> <%= @article.author %> </b></p>

<% if @article.picture.exists? %>
    <a href="<%= @article.picture.url %>">
      <%= image_tag @article.picture.url :medium %>
    </a>
<% end %>

<p>
  <%= @article.content %>
</p>

<% if current_user.try :has_access_to?, @article %>
    <%= link_to 'Edit', edit_article_path(@article) %> |
    <%= link_to 'Delete', @article, method: :delete, data: {confirm: 'Are you sure?'} %> |
<% end %>
<%= link_to 'Back', articles_path %>

<h2>Comments</h2>

<%= render 'comments/form' %>

<div class="comments">
  <%= render @article.comments %>
</div>

app/views/comments/_comment.html.erb
<div class="comment" id="<%= "comment-#{comment.id}" %>">

  <p>
    <%= comment.posted_at %>
    <b><%= comment.author or 'Anonymous' %></b>
  </p>

  <% if current_user.try :has_access_to?, comment %>
      <p class="rest-in-place"
         data-object="comment"
         data-url="<%= article_comment_path @article, comment %>"
         data-attribute="content">
        <%= comment.content %>
      </p>
      <%= link_to "Delete", article_comment_path(@article, comment), remote: true, method: :delete %>
  <% else %>
      <p>
        <%= comment.content %>
      </p>
  <% end %>

</div>

app/views/comments/_form.html.erb
<%= form_for([@article, @comment], remote: true) do |f| %>
    <div class="field">
      <%= f.text_field :content %>
      <%= f.submit 'Comment' %>
    </div>
<% end %>

app/views/comments/create.js.erb
var comment = $("<%= escape_javascript(render @comment) %>");
comment.prependTo(".comments");
comment.find('.rest-in-place').restInPlace();
$('input#comment_content').val('');

app/views/comments/destroy.js.erb
var comment = $('<%= "#comment-#{@comment.id}" %>');
comment.remove();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'partials/header' %>

<div class="flash-messages">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>

<%= yield %>

</body>
</html>

app/views/partials/_header.html.erb
<div>
  <% if user_signed_in? %>
      Signed in as <b> <%= current_user.username %> </b> (<%= current_user.role %>)
      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
  <% else %>
      <%= link_to 'Log in', new_user_session_path %>
      <%= link_to 'Sign up', new_user_registration_path %>
  <% end %>
  <br>
  <%= link_to 'Articles', :articles %>
</div>